apiVersion: v1
kind: Service
metadata:
  name: smartops-service
  namespace: tenant-a
spec:
  selector:
    app: smartops-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
